// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: mapper.sql

package dbgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const finishCrawlRun = `-- name: FinishCrawlRun :exec
UPDATE crawl_runs
SET status = $2,
	finished_at = now(),
	discovered_count = $3,
	page_count = $4,
	error_count = $5
WHERE id = $1
`

type FinishCrawlRunParams struct {
	ID              int64
	Status          string
	DiscoveredCount int64
	PageCount       int64
	ErrorCount      int64
}

func (q *Queries) FinishCrawlRun(ctx context.Context, arg FinishCrawlRunParams) error {
	_, err := q.db.Exec(ctx, finishCrawlRun,
		arg.ID,
		arg.Status,
		arg.DiscoveredCount,
		arg.PageCount,
		arg.ErrorCount,
	)
	return err
}

const getDomainIDByDomain = `-- name: GetDomainIDByDomain :one
SELECT id FROM domains WHERE domain = $1
`

func (q *Queries) GetDomainIDByDomain(ctx context.Context, domain string) (int64, error) {
	row := q.db.QueryRow(ctx, getDomainIDByDomain, domain)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const insertPipelineEvent = `-- name: InsertPipelineEvent :exec
INSERT INTO pipeline_events (service, event_type, domain_id, crawl_run_id, url_id, document_id, version_id, payload)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
`

type InsertPipelineEventParams struct {
	Service    string
	EventType  string
	DomainID   pgtype.Int8
	CrawlRunID pgtype.Int8
	UrlID      pgtype.Int8
	DocumentID pgtype.Int8
	VersionID  pgtype.Int8
	Payload    []byte
}

func (q *Queries) InsertPipelineEvent(ctx context.Context, arg InsertPipelineEventParams) error {
	_, err := q.db.Exec(ctx, insertPipelineEvent,
		arg.Service,
		arg.EventType,
		arg.DomainID,
		arg.CrawlRunID,
		arg.UrlID,
		arg.DocumentID,
		arg.VersionID,
		arg.Payload,
	)
	return err
}

const listURLsForDomain = `-- name: ListURLsForDomain :many
SELECT id, domain_id, url, last_crawl_run_id
FROM urls
WHERE domain_id = $1
ORDER BY id
`

type ListURLsForDomainRow struct {
	ID             int64
	DomainID       int64
	Url            string
	LastCrawlRunID pgtype.Int8
}

func (q *Queries) ListURLsForDomain(ctx context.Context, domainID int64) ([]ListURLsForDomainRow, error) {
	rows, err := q.db.Query(ctx, listURLsForDomain, domainID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListURLsForDomainRow
	for rows.Next() {
		var i ListURLsForDomainRow
		if err := rows.Scan(
			&i.ID,
			&i.DomainID,
			&i.Url,
			&i.LastCrawlRunID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const startCrawlRun = `-- name: StartCrawlRun :one
INSERT INTO crawl_runs (domain_id, seed_url, status)
VALUES ($1, $2, 'running')
RETURNING id
`

type StartCrawlRunParams struct {
	DomainID int64
	SeedUrl  string
}

func (q *Queries) StartCrawlRun(ctx context.Context, arg StartCrawlRunParams) (int64, error) {
	row := q.db.QueryRow(ctx, startCrawlRun, arg.DomainID, arg.SeedUrl)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const upsertDomain = `-- name: UpsertDomain :one
INSERT INTO domains (domain, created_at, updated_at)
VALUES ($1, now(), now())
ON CONFLICT (domain)
DO UPDATE SET updated_at = now()
RETURNING id, domain
`

type UpsertDomainRow struct {
	ID     int64
	Domain string
}

func (q *Queries) UpsertDomain(ctx context.Context, domain string) (UpsertDomainRow, error) {
	row := q.db.QueryRow(ctx, upsertDomain, domain)
	var i UpsertDomainRow
	err := row.Scan(&i.ID, &i.Domain)
	return i, err
}
