// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package dbgen

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type CrawlRun struct {
	ID              int64
	DomainID        int64
	SeedUrl         string
	Status          string
	StartedAt       pgtype.Timestamptz
	FinishedAt      pgtype.Timestamptz
	DiscoveredCount int64
	PageCount       int64
	ErrorCount      int64
}

type Domain struct {
	ID        int64
	Domain    string
	CreatedAt pgtype.Timestamptz
	UpdatedAt pgtype.Timestamptz
}

type NodeHeartbeat struct {
	Service    string
	Status     string
	Details    []byte
	LastSeenAt pgtype.Timestamptz
}

type NodeMetric struct {
	ID          int64
	Service     string
	MetricName  string
	MetricValue float64
	Labels      []byte
	RecordedAt  pgtype.Timestamptz
}

type PageDocument struct {
	ID                int64
	DomainID          int64
	UrlID             pgtype.Int8
	Url               string
	UrlHash           []byte
	FinalUrl          pgtype.Text
	Title             pgtype.Text
	Language          pgtype.Text
	ContentType       pgtype.Text
	StatusCode        pgtype.Int4
	DocumentType      string
	SourceUrl         pgtype.Text
	LatestContentHash []byte
	LatestHtmlHash    []byte
	LatestVersionID   pgtype.Int8
	LastParsedAt      pgtype.Timestamptz
	LastError         pgtype.Text
	CreatedAt         pgtype.Timestamptz
	UpdatedAt         pgtype.Timestamptz
}

type PageDocumentSource struct {
	ID          int64
	DocumentID  int64
	SourceUrl   string
	LinkUrl     string
	FirstSeenAt pgtype.Timestamptz
	LastSeenAt  pgtype.Timestamptz
}

type PageDocumentVersion struct {
	ID           int64
	DocumentID   int64
	ContentHash  []byte
	HtmlHash     []byte
	Title        pgtype.Text
	Language     pgtype.Text
	Markdown     string
	StatusCode   pgtype.Int4
	ContentType  pgtype.Text
	FinalUrl     pgtype.Text
	DocumentType string
	SourceUrl    pgtype.Text
	ParsedAt     pgtype.Timestamptz
	CreatedAt    pgtype.Timestamptz
}

type PageParseError struct {
	ID        int64
	DomainID  pgtype.Int8
	Url       string
	UrlHash   []byte
	Error     string
	CreatedAt pgtype.Timestamptz
}

type PipelineEvent struct {
	ID         int64
	Service    string
	EventType  string
	DomainID   pgtype.Int8
	CrawlRunID pgtype.Int8
	UrlID      pgtype.Int8
	DocumentID pgtype.Int8
	VersionID  pgtype.Int8
	Payload    []byte
	CreatedAt  pgtype.Timestamptz
}

type Url struct {
	ID             int64
	DomainID       int64
	Url            string
	UrlHash        []byte
	FirstSeenAt    pgtype.Timestamptz
	LastSeenAt     pgtype.Timestamptz
	LastCrawlRunID pgtype.Int8
}
