// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: monitor.sql

package dbgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const listDomains = `-- name: ListDomains :many
SELECT id, domain, created_at, updated_at
FROM domains
ORDER BY updated_at DESC, id DESC
LIMIT $1 OFFSET $2
`

type ListDomainsParams struct {
	Limit  int32
	Offset int32
}

func (q *Queries) ListDomains(ctx context.Context, arg ListDomainsParams) ([]Domain, error) {
	rows, err := q.db.Query(ctx, listDomains, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Domain
	for rows.Next() {
		var i Domain
		if err := rows.Scan(
			&i.ID,
			&i.Domain,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRecentRuns = `-- name: ListRecentRuns :many
SELECT cr.id, d.domain, cr.seed_url, cr.status, cr.started_at, cr.finished_at,
       cr.discovered_count, cr.page_count, cr.error_count
FROM crawl_runs cr
JOIN domains d ON d.id = cr.domain_id
ORDER BY cr.started_at DESC
LIMIT $1
`

type ListRecentRunsRow struct {
	ID              int64
	Domain          string
	SeedUrl         string
	Status          string
	StartedAt       pgtype.Timestamptz
	FinishedAt      pgtype.Timestamptz
	DiscoveredCount int64
	PageCount       int64
	ErrorCount      int64
}

func (q *Queries) ListRecentRuns(ctx context.Context, limit int32) ([]ListRecentRunsRow, error) {
	rows, err := q.db.Query(ctx, listRecentRuns, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListRecentRunsRow
	for rows.Next() {
		var i ListRecentRunsRow
		if err := rows.Scan(
			&i.ID,
			&i.Domain,
			&i.SeedUrl,
			&i.Status,
			&i.StartedAt,
			&i.FinishedAt,
			&i.DiscoveredCount,
			&i.PageCount,
			&i.ErrorCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
