// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: parser.sql

package dbgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getURLForParse = `-- name: GetURLForParse :one
SELECT u.id, u.domain_id, d.domain, u.url, u.url_hash, u.last_crawl_run_id
FROM urls u
JOIN domains d ON d.id = u.domain_id
WHERE u.id = $1
`

type GetURLForParseRow struct {
	ID             int64
	DomainID       int64
	Domain         string
	Url            string
	UrlHash        []byte
	LastCrawlRunID pgtype.Int8
}

func (q *Queries) GetURLForParse(ctx context.Context, id int64) (GetURLForParseRow, error) {
	row := q.db.QueryRow(ctx, getURLForParse, id)
	var i GetURLForParseRow
	err := row.Scan(
		&i.ID,
		&i.DomainID,
		&i.Domain,
		&i.Url,
		&i.UrlHash,
		&i.LastCrawlRunID,
	)
	return i, err
}

const insertParseError = `-- name: InsertParseError :exec
INSERT INTO page_parse_errors (domain_id, url, url_hash, error, created_at)
VALUES ($1, $2, $3, $4, now())
`

type InsertParseErrorParams struct {
	DomainID pgtype.Int8
	Url      string
	UrlHash  []byte
	Error    string
}

func (q *Queries) InsertParseError(ctx context.Context, arg InsertParseErrorParams) error {
	_, err := q.db.Exec(ctx, insertParseError,
		arg.DomainID,
		arg.Url,
		arg.UrlHash,
		arg.Error,
	)
	return err
}

const lookupURLID = `-- name: LookupURLID :one
SELECT id FROM urls WHERE domain_id = $1 AND url_hash = $2
`

type LookupURLIDParams struct {
	DomainID int64
	UrlHash  []byte
}

func (q *Queries) LookupURLID(ctx context.Context, arg LookupURLIDParams) (int64, error) {
	row := q.db.QueryRow(ctx, lookupURLID, arg.DomainID, arg.UrlHash)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const updateDocumentError = `-- name: UpdateDocumentError :exec
UPDATE page_documents
SET last_error = $3,
	last_parsed_at = now(),
	updated_at = now()
WHERE domain_id = $1 AND url_hash = $2
`

type UpdateDocumentErrorParams struct {
	DomainID  int64
	UrlHash   []byte
	LastError pgtype.Text
}

func (q *Queries) UpdateDocumentError(ctx context.Context, arg UpdateDocumentErrorParams) error {
	_, err := q.db.Exec(ctx, updateDocumentError, arg.DomainID, arg.UrlHash, arg.LastError)
	return err
}
