// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: vectorizer.sql

package dbgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getDocumentVersionForVectorize = `-- name: GetDocumentVersionForVectorize :one
SELECT
	d.id AS document_id,
	v.id AS version_id,
	d.url,
	domains.domain,
	v.title,
	v.language,
	v.markdown,
	encode(v.content_hash, 'hex') AS content_hash,
	v.status_code,
	v.content_type,
	v.final_url,
	v.document_type,
	v.source_url,
	v.parsed_at
FROM page_document_versions v
JOIN page_documents d ON d.id = v.document_id
JOIN domains ON domains.id = d.domain_id
WHERE d.id = $1
  AND v.id = $2
LIMIT 1
`

type GetDocumentVersionForVectorizeParams struct {
	ID   int64
	ID_2 int64
}

type GetDocumentVersionForVectorizeRow struct {
	DocumentID   int64
	VersionID    int64
	Url          string
	Domain       string
	Title        pgtype.Text
	Language     pgtype.Text
	Markdown     string
	ContentHash  string
	StatusCode   pgtype.Int4
	ContentType  pgtype.Text
	FinalUrl     pgtype.Text
	DocumentType string
	SourceUrl    pgtype.Text
	ParsedAt     pgtype.Timestamptz
}

func (q *Queries) GetDocumentVersionForVectorize(ctx context.Context, arg GetDocumentVersionForVectorizeParams) (GetDocumentVersionForVectorizeRow, error) {
	row := q.db.QueryRow(ctx, getDocumentVersionForVectorize, arg.ID, arg.ID_2)
	var i GetDocumentVersionForVectorizeRow
	err := row.Scan(
		&i.DocumentID,
		&i.VersionID,
		&i.Url,
		&i.Domain,
		&i.Title,
		&i.Language,
		&i.Markdown,
		&i.ContentHash,
		&i.StatusCode,
		&i.ContentType,
		&i.FinalUrl,
		&i.DocumentType,
		&i.SourceUrl,
		&i.ParsedAt,
	)
	return i, err
}
